### ISSUE TITLE
Update details redirect error

### ISSUE THREAD

**Issue by bnkosi2019** [kaysiz/matcha-wtc-2019#4]
**Webpage:**
Method Not Allowed
The method is not allowed for the requested URL.

**Console**
127.0.0.1 - - [02/Dec/2019 13:36:36] "POST /profile?next=http%3A%2F%2F127.0.0.1%3A5000%2F HTTP/1.1" 405 -

**Comment by bnkosi2019** [comment]
OK so we sorted it out. the @route needed a get method as well ie:
profile.py line 27:
@user.route('/profile',  methods=['GET', 'POST'])

we ridrected the user back to login:
profile.py line 61:
return redirect( url_for('auth.login') )

that shit works. we dont know how to redrct to profile. but this works, user has to log back in again cause they changed their deats

**Comment by Petsoane** [comment]
Line 67 is fixed, just redirect to profile.profile
( URL_for( profile. Profile))

**Comment by Petsoane** [comment]
I have also fixed this issue
