### ISSUE TITLE
Geolocation on profile completion

### ISSUE THREAD

**Issue by bnkosi2019** [kaysiz/matcha-wtc-2019#6]
I've completed this geolocation: only issue is that it picks up the location on server in cape town not the location of this mac -> need help please

**Comment by kaysiz** [comment]
Ok no problem, i will pick it up. What is the branch that you are working on?

**Comment by bnkosi2019** [comment]
Sorted out the problem. all details including location update to db now. just need validation on that data going in

**Comment by bnkosi2019** [comment]
Accidentally closed this. Still need a way for user to input their locatio
