### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by bnkosi2019** [kaysiz/matcha-wtc-2019#8]
Vaughan has done validations on registration details. Need to do the same for login and posts so no sql inj and all that shit

**Comment by bnkosi2019** [comment]
profile.py
Profile and bio update info needs validations -> check the info coming in is legit and all that

**Comment by VR-Scott** [comment]
I will work on the profile and bio ones now and then work on email confirmation check in login after that. I at some point will also try to Implement escaping of all inputs to protect agains inj.
